const jobTypes = [
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "Graphic Designer",
    "UX/UI Designer",
    "DevOps Engineer",
    "Database Administrator",
    "Cybersecurity Analyst",
    "Systems Analyst",
    "Network Engineer",
    "Cloud Architect",
    "AI/ML Engineer",
    "QA Engineer",
    "Full Stack Developer",
    "Front End Developer",
    "Back End Developer",
    "Mobile Developer",
    "IT Support Specialist",
    "Business Analyst",
    "Project Manager",
    "Technical Writer",
    "Sales Engineer",
    "IT Manager",
    "ERP Consultant",
    "Solutions Architect",
    "Business Intelligence Analyst",
    "Hardware Engineer",
    "Help Desk Technician",
    "Game Developer",
    "Blockchain Developer"
  ];
export {jobTypes}  